### ISSUE TITLE
Ability to hide Results Panel

### ISSUE THREAD

**Issue by sobanhameed** [ghinda/jotted#11]
If there is an option to hide results panel that will be great. This will come in handy in scenarios if someone is just writing javascript and wants to show output in console.

**Comment by ghinda** [comment]
You can use CSS for that. Here's a demo:
http://jsbin.com/rofofo/edit?html,css,js,output

And you can even implement your own renderer, since the iframe renderer is just a plugin:
https://github.com/ghinda/jotted/blob/master/src/plugins/render.js

**Comment by sobanhameed** [comment]
Thanks :+1:
