### ISSUE TITLE
Show console panel at the bottom

### ISSUE THREAD

**Issue by sobanhameed** [ghinda/jotted#12]
If there is an option to show console panel at the bottom(horizontally below) instead of side by side as panel that will be great. This way the user wont have to change tabs to be able to see console output if they are not using the bin theme. Let me know if you think it makes sense.

**Comment by ghinda** [comment]
You can use CSS for that:
http://jsbin.com/qaxema/edit?html,css,js,output

**Comment by sobanhameed** [comment]
Thanks :+1:
