### ISSUE TITLE
Play + Console - autoClear Issue

### ISSUE THREAD

**Issue by sobanhameed** [ghinda/jotted#13]
I have noticed this issue with Play plugin and console-autoClear set to True. When nothing has changed and I click Run it clears the console (prev result) and doesn't print the log lines. It looks that execution doesn't happen when nothing has changed. I recommend that we force Execute on run click. Thoughts? Let me know if you want me to provide jsbin for repro.

**Comment by ghinda** [comment]
Fixed in the latest version (`1.3.1`). 

The Run button in the Play plugin will now always force rendering, even if the content hasn't changed.
The console will only auto-clear if the content has changed, or rendering is forced.

**Comment by sobanhameed** [comment]
Thanks again.
