### ISSUE TITLE
For Play Plugin hold off the first execution until Run is pressed

### ISSUE THREAD

**Issue by sobanhameed** [ghinda/jotted#14]
Currently I see that first execution happens immediately. Can we hold off execution until Run is pressed?

**Comment by ghinda** [comment]
So you don't want to have anything ran when the plugin is initialized? I could add an option for it, in the play plugin.

**Comment by ghinda** [comment]
Implemented as an option to the `play` plugin. Set `firstRun` to false.

Here's a demo:
https://ghinda.net/jotted/demos/play.html
