### ISSUE TITLE
Console errors are not shown

### ISSUE THREAD

**Issue by sobanhameed** [ghinda/jotted#16]
I have noticed that console errors dont shown at times.

```
for(let i = 0; i < 10; i++) { /* … */ }
for(let i = 0; i < 10; i++) { /* … */ }
console.log(i) // ERROR: no global i declared
```
Error shows on browser console but not on jotted console.

Can we get the errors on jotted console?

**Comment by ghinda** [comment]
That's right. The `console` plugin doesn't catch errors, unless you make them directly in the console repl. 

I can't implement error reporting in the console right now, but I'd happy to take a look at a pull request.
