### ISSUE TITLE
Force run with play plugin

### ISSUE THREAD

**Issue by AWolf81** [ghinda/jotted#17]
@ghinda,
at the moment, I'm writing an angular wrapper directive for jotted and it's working very well.
(Wrapper not on github yet.)

So my problem is that I'm loading async. data from a gist and then I'd like to re-run the code after loading to have the updated result but active play plugin isn't running the code after load. Is there a way to do this with the play plugin?

I've had a look at the source code and couldn't see anything like this. That's why I've added it to a fork of your repo. Please have a look [here](https://github.com/AWolf81/jotted/tree/play-forcerun). (In the fork I've also changed mocha test env. a bit because Sauselab wasn't working for me.)

Is there any side effect of my added code? I'm passing a new property `updatedData = { ... play: {forceRun: true}}` to `jotted.trigger('change', updatedData)`. The added test is passing and no other test is failing.

One issue I've noticed is that I can't trigger the change at every content / type and only at the last content. That's why I have something like this in my AngularJs code where I'm preparing the data for jotted:

    config.files.push({
        type: curMappedLang, // mapping where needed
        content: file.content,
        play: {
            // force run on last load item, otherwise css was not loaded properly
            forceRun: (fileNames.length - 1 === i)
        }
    });

Later in my angular code I'm triggering the change like this:

    for (let i=0; i < config.files.length; i++) {
        jotted.trigger('change', angular.copy(config.files[i]));
    }

It's OK to have that in my code and it's working but re-usability isn't good. It would be better if there would be a way to replace every jotted data at once (no looping to trigger changes for html, js, css pane) and trigger the play plugin to run the new data. Or is this already possible?

**Comment by ghinda** [comment]
Hi,

The issue you're having with the CSS not loading could be because you're calling `trigger` right after initializing jotted. This causes your trigger function to be caught by the debouncer, and not ran. 
A quick fix would be to set `debounce: false` in the options.

If you create a jsbin for it, I can take a look.

When loading the file content async, I would not initialize the widget until all files are loaded. The `trigger` method does not change the textarea/editor content, only the result, so it's not really meant to be used for this.

Here's how I would load some gists:
http://jsbin.com/sojani/edit?js,output

**Comment by AWolf81** [comment]
I think waiting for the async data is not possible because I'd like to have that as optional feature. So the editor can be used with-out loading a gist. But maybe I can destroy the jotted instance and create a new one.
I have to check if that's easier to do.

Please have a look at this [jsfiddle](https://jsfiddle.net/awolf2904/79z5o7sf/) of my current work.

At line 10 in the fiddle, I've commented the url to the unmodified source. Just add it and comment the next line to see the different loading.

The directive code that's using jotted is in this [repo](https://github.com/AWolf81/angular-jotted).

**Comment by ghinda** [comment]
Yeah, the best approach would be to re-initialize Jotted. Just remove the dom node, create a new one and init Jotted on it.

Still, if you really need to load the files after initializing jotted, there is a way using some undocumented methods. I'm not planning on changing/removing them any time soon, but be warned.

I updated the jsbin with two examples on how to load files after jotted is initialized, with and without the play plugin:
http://jsbin.com/sojani/edit?js,output
