### ISSUE TITLE
a full blown solution

### ISSUE THREAD

**Issue by omidfi** [ghinda/jotted#19]
hi, how could be possible to make a full stack solution like a small jsfiddle up and running using jotted? 
Is this just the frontend?

**Comment by ghinda** [comment]
You'll need a back-end to save the edited content. You could use the GitHub Gist API, or something similar.

You don't need a lot of code for the Jotted integration.

Here's a simple demo that saves all the changes you make to local storage, so they're still there after you refresh the browser:
http://jsbin.com/sebibax/edit?js,output
