### ISSUE TITLE
Load dependency libs for showcase.

### ISSUE THREAD

**Issue by armoucar** [ghinda/jotted#20]
How about loading libs that may be used in showcases? I tried to find this feature inside the code but I couldn't. Is that something that `jotted` already does or should it be developed?

An example would be jQuery, but I mean a feature to load any js lib.

Thanks, the project is great.

**Comment by armoucar** [comment]
In fact, that worked well only by adding the scripts/css tags inside the html I want to demonstrate. Tried that because of a cool comment in #3 

It's not a big deal, but it'd be nicer if I could tell `jotted` those dependencies, in this case, there wouldn't be any script/link tags inside my HTML editor. If this is something you're interested on merging in the project, maybe I could spend some time on this feature.

Thanks :)

**Comment by armoucar** [comment]
The events API was enough to create a solution for my case. `Jotted` is so simple and at the same time so extensible. Now I don't event think `jotted` should provide a way of 'importing' dependencies. Keep it small and extensible, that's sufficient. My solution isn't sophisticated but right now, solves my problem. I'll paste it in here in case someone goes through the same problem:

```
var reScript = /<script[\s\S]*?>[\s\S]*?<\/script>/gi,
    reLinks = /<link[\s\S]*?>[\s\S]*?(<\/link>)*/gi,
    scripts = [],
    links = [],
    firstExecution = true;

jotted.on('change', function (params, callback) {
  if (firstExecution) {
    firstExecution = false;

    scripts = params.cmEditor.getValue().match(reScript);
    links = params.cmEditor.getValue().match(reLinks);

    var visualCode = params
                      .cmEditor
                      .getValue()
                      .replace(reScript, '')
                      .replace(reLinks, '')
                      .trim();

    params.cmEditor.setValue(visualCode);
  }

  var toRender = '';
  if (scripts.length) toRender += scripts.join('\n');
  if (links.length) toRender += links.join('\n');

  params.content = toRender + params.content;

  callback(null, params)
});
```

**Comment by ghinda** [comment]
This sounds like a good idea for a plugin! :electric_plug:

I created a small demo of how it could work:
http://jsbin.com/togucih/edit?js,output

It supports full urls or library names (eg. `jquery`).

**Comment by bhoot-biswas** [comment]
How can I add resource between `head` tags?
