### ISSUE TITLE
Support for multiple files

### ISSUE THREAD

**Issue by naeemulhaque** [ghinda/jotted#22]
Can we add support for multiple files (js, css), something like thimble.mozilla.org or plnkr.co?

**Comment by ghinda** [comment]
This would require lots of core and UI changes, so I'm not planning on implementing it right now.

Thanks for the suggestion. If more people ask for it, I'll re-open.

**Comment by jasonday** [comment]
I think this would be possible by adding the following options:
```
styles: [],
scripts: []
```
with urls as comma separated arrays. Then on template render, include these elements in the iframe. I haven't had time to look at the code in depth, but this seems like a relatively simple addition,
