### ISSUE TITLE
how to run this?

### ISSUE THREAD

**Issue by suriyaJaay** [ghinda/jotted#25]
could anyone tell me how to run this after installing as per doc?

do i need run by like this  node xxxx.js ? on which port it will run. ?

**Comment by armoucar** [comment]
I'm suppose you mean run this project locally on your computer, right?

After clone it, you should npm install. Make sure you also have grunt installed: `npm install -g grunt-cli`.

You'll have some grunt tasks to run, but if you want to run jotted's website, just run: `grunt server`. It'll put a local server up running on port 9000.

**Comment by ghinda** [comment]
Hi @suriyaJaay,

If you want to contribute to Jotted and send me a pull request, follow @armoucar instructions above.

If you just want to use it on your website, you can use it directly from a CDN.
See this basic demo:
http://jsbin.com/yebebo/edit?html,js,output

More instructions here:
https://github.com/ghinda/jotted/blob/master/README.md

Demos here:
https://ghinda.net/jotted/#demos

Jotted is only a front-end library, so it doesn't handle saving files anywhere. You can create a plugin for that.

If you want a complete solution, jsbin.com is free software: 
https://github.com/jsbin/jsbin
