### ISSUE TITLE
Height of pane / iframe

### ISSUE THREAD

**Issue by Mik-A** [ghinda/jotted#26]
EDIT!

Finally found a way with css
So this can be closed as solved. Thank you and sorry for the inconvinience.
/*
Hello

'I have difficulties changing the height of the result pane. Or the whole pane. I tried with by adding a div with new class around the iframe and then css it to dynamic according to content. Didnt work. Or changing .jotted-pane-result did work nor any static height. So I'm lost here. 
I think it is just too narrow to see the actual result. Now 150px only. Can you please help?

**Comment by ghinda** [comment]
You can set the height directly on the main container.

Here:
http://jsbin.com/dehoka/edit?html,css,output

**Comment by Mik-A** [comment]
No, that is not working.
This did:
.jotted
{height: 100%;}
.jotted-pane-result iframe, .jotted-editor textarea {
  width: 100%;
  height: 500px;
}

**Comment by ghinda** [comment]
Is the demo not working? What browser are you using?

This is how it looks on my end in Firefox and Chrome:
![screenshot_20161013_095908](https://cloud.githubusercontent.com/assets/325171/19339406/dc919ca0-912b-11e6-8376-93ecfdd7122f.png)

**Comment by Mik-A** [comment]
Firefox. Yes the demo works. But cannot apply that to my own jotted fiddle I aim to host. Changing height of container has no effect what so ever.
But my example of css did do it.

**Comment by Mik-A** [comment]
I would give you a link if my server was up and running..
doing it locally only for the moment
