### ISSUE TITLE
Add content between head tags

### ISSUE THREAD

**Issue by bhoot-biswas** [ghinda/jotted#28]
Hi,

Is it possible to add content between `<head>` and `</head>` tags? Actually, I want and insert CSS or JS links there. Hope there has a way.

Thanks.

**Comment by ghinda** [comment]
You can't add anything to the `head` tag directly. Your content will be added to the `body`, but you can still use `link` or `script` tags there.

Here's a simple demo for loading jQuery and Bootstrap:
http://jsbin.com/woneka/edit?html,js,output

**Comment by jasonday** [comment]
Why not just include options for script, css, etc.  and when the iframe is created, add those?
