### ISSUE TITLE
content line disappears

### ISSUE THREAD

**Issue by suriyaJaay** [ghinda/jotted#32]
jotted is loaded fine for the first time. but suddenly the content line goes up and down when try to edit the content. it has happened after getting back from some other part of the my module. pls find the below image 

**1st image shows complete code with no issues**
![ace1](https://cloud.githubusercontent.com/assets/19813670/20130247/895cc004-a67b-11e6-945e-dfd7f9e47421.PNG)
**2nd images show . some line has disappear when try to edit the code**
![ace2](https://cloud.githubusercontent.com/assets/19813670/20130248/8960bed4-a67b-11e6-954c-998dff68300e.PNG)

what is problem actually? where should i change it.?

i try to change "ace_content" class height dynamically from height: 490px; to height: auto; but it doesn't accept it 

Thank you

**Comment by ghinda** [comment]
Hi,

I can't replicate your exact issue. Can you create a http://jsbin.com/ demo?

**Comment by suriyaJaay** [comment]
@ghinda  am trying to replicate it.between that. trying to use code mirror plugin. could you pls tell me how to css and js pane .

i tried to add css and js pane  after html but shows as fallows
![jotcodem](https://cloud.githubusercontent.com/assets/19813670/20134824/e3f359e4-a692-11e6-9924-08e4a85c5c1a.PNG)

**Comment by ghinda** [comment]
Please make a http://jsbin.com for it, so I can see your config.

In the meanwhile, here's a how to use the codemirror plugin:
https://ghinda.net/jotted/demos/codemirror.html

**Comment by suriyaJaay** [comment]
brother i actually complete as per the document from above link.its working fine.
 what am asking how can add "css and js" pane in this editor. ?
by using ace plugin i got RESULT, HTML, CSS ,JS part in jotted ui. the same thing i want when i use codemirror.

**Comment by suriyaJaay** [comment]
@ghinda now i got cleared it myself.. working fine.. thanks for your quick response

**Comment by ghinda** [comment]
To have all the panes visible - even with no content, you can use the `showBlank` option:
https://github.com/ghinda/jotted#showblank

**Comment by suriyaJaay** [comment]
sorry, am again. how to change theme for codemirror.

i did changed theme in ace editor .. now i want to change theme for codemirror

**Comment by armoucar** [comment]
@suriyaJaay hack, brother... hack.

**Comment by suriyaJaay** [comment]
ha aha h lols @armoucar  sure ll do that by my own

**Comment by ghinda** [comment]
@suriyaJaay here you go:
http://jsbin.com/qaneqoc/edit?html,js,output

Load the CSS theme and pass the `theme` option. This is a CodeMirror option.

You can pass any specific options to plugins, using the `options` object, as described in the documentation:
https://github.com/ghinda/jotted#plugins
