### ISSUE TITLE
Including the codemirror plugin in gulp-angular

### ISSUE THREAD

**Issue by bryantmakesprog** [ghinda/jotted#35]
I am trying to use the Jotted javascript library in conjunction with a gulp-angular project. The library itself works fine, but I'm trying to include the library's Codemirror plugin and am running into issues. When I try to add the library and run gulp serve, I get this error:

`Error in parsing: "js/codemirror.js", Line 4: Unexpected reserved word`

The line causing the issue looks like so:

`import * as util from '../util.js'`

**Comment by ghinda** [comment]
The main library file `jotted.js`/`jotted.min.js` already includes all the plugins in the docs (including the CodeMirror plugin), so you don't have to include them separately.

You'll just need to include the actual CodeMirror files:
* With bower (eg. https://ghinda.net/jotted/demos/codemirror.html)
* From a cdn (https://cdnjs.com/libraries/codemirror)
