### ISSUE TITLE
Persist / Store changes (serialize editor)

### ISSUE THREAD

**Issue by zoernert** [ghinda/jotted#37]
It would be nice to have some sort of function that allows to easily serialize an object of the editor's content into a single object which might be stored and restored in future.

**Comment by ghinda** [comment]
You can do that with the `on()` event api:
http://s.siloz.io/C

In production you could wrap the change function in a plugin:
```
Jotted.plugin('store', function (j, options) {
  j.on('change', ...)
});
```

**Comment by zoernert** [comment]
Great Thanks! That was what I was looking for!

**Comment by armoucar** [comment]
Jotted is super well designed. Congratz ghinda. 🥇
