### ISSUE TITLE
Using the pen plugin without the codemirror plugin makes the result panel disappear on focus

### ISSUE THREAD

**Issue by victorloux** [ghinda/jotted#40]
Thanks a lot for this amazing tool!

I'm experiencing a strange issue with the pen plugin. You can try it yourself on the [demo page of the plugin](https://ghinda.net/jotted/demos/pen.html). It works fine in the example provided, but if you remove the plugin `codemirror` from the array list (i.e. to only have textareas, not a code editor), then **clicking on any of the code textareas causes the result panel (on top) to disappear**, and all the code panels shift up.

Issue happens consistently on Chrome, Firefox and IE, and also outside of the demo environment. The pen plugin doesn't seem to have any dependency on the codemirror plugin, I've had a look but was not able to fix it myself. It doesn't happen with the bin plugin.

**Comment by ghinda** [comment]
Thanks for reporting the bug! 🍺 
Fixed in the latest version `1.5.2`.
