### ISSUE TITLE
Select each element separately

### ISSUE THREAD

**Issue by dink** [ghinda/jotted#44]
I'm trying to select each element (HTML, CSS, JS) separately before saving it to a file or database, so if I write the following into the HTML:

`<h2>Hello World!</h2>`

I want just that, nothing else. Same for CSS and JS. 

Is there a way to grab these via js by element id or something similar? or a way to define it first?

If I write: 
`var jotted = document.getElementById("jotted_content").innerHTML`
it grabs the whole thing with all the iframes and whatnot. 

Thanks, great tool btw.

**Comment by ghinda** [comment]
Sure, you can create a small plugin for that. No need to look into the DOM directly.

Here's a demo: [jotted-change-demo](https://www.siloz.io/#s=N4IgbgpgTgzglgewHYgFwEYA0IBmcA2EMaA2qAC4CeADhGiABbkC2+I2AxsuREufQB58cJAGsABFAj4AvAB0QMKoRgMIEcgvFVa8kDwAe5APQcYMLQyk49TctRipjpgCZIAdACsYL6XDBQ7kgaxkjUzMaeCOQ8LgAC+ACGPEqR0bHuzCLuZhYgAHxySAIwHFBw1OTiMFActjEOTq4e3r7CAUEhYRFRMRDxSSkmvRlZLXn5Asal5ZWFSEVFAi7+4nAuer0Kk8YrYPkgAL6YFDR0qCC57JfcvPwXRyf6Z-Te11x8d-QAUun97tR8ABXADmIgAFAByJQIKSQzDiHBApAcciIJDicGeBEISromAASnEwCK4nEnncyChHAYiSQIIg8Mx1ESUESzBgCI4iXw+AARokOKIiTJ8sTSWTxB8YAhCO58AgQeCWWyOQSJWTnIjkaj0eIAO4EfDiPkQKU8wgucQAZm0cGYRA14i1yDNOFh4gggoY2jOmNyCKYrC55nVGMlcBwzNZ7Jg7h0ZpkSfEkKD+EhRJJ4clzuMBthEkN5B9aadhydTsj0dVcYT4iTMhTuQz4uzkq1+oLBrgxal5jLFbb3N5AqF4KQQN5CJVsbDZMOYYXAG5FgskMF9eJfn0XOCXAgOECHXx3ABHIHQSgAZWkEFRsKhAGJehmEVmc3gVKhxCQneI5OQ745v+mgxGc36piw6aYH+IEAR8PB8BBADCtx8JCsHzjBbZkgBQHASBCYQc22EEbh5AIXcEF8ggLiUMSJqCqIIJQAgyIuN+DDRNQIiiEu4iHBhOEgeWbYALqkQBgKgiIjg-tC5CwoyYkSguRRHBJIDSWCSDEKgJCacWEAOvQMpJOUABe-TiMIIJMNcLLBHpoBXKgoAMOsvgoKg5BQBexyMFBaDAAFbxuYcEVAA)

It uses the `on('change', ..)` method in the [Events API](https://github.com/ghinda/jotted#events-api).
```
Jotted.plugin('store', function (j, options) {
  j.on('change', ...)
});
```

**Comment by dink** [comment]
Thank you, I will try this method.
