### ISSUE TITLE
Codepen like Console output

### ISSUE THREAD

**Issue by sobanhameed** [ghinda/jotted#7]
Codepen recently launched console pane. Are you planning to do anything similar? 

https://blog.codepen.io/2016/01/27/new-feature-javascript-console/

Also if jotted can provide a hook to console functions then users can build their own console view.

**Comment by ghinda** [comment]
I wasn't planning on it, but I'll definitively take a look and see what can be done.

**Comment by ghinda** [comment]
Aand it's done.
![jotted-console](https://cloud.githubusercontent.com/assets/325171/12979090/b12b1e1a-d0dd-11e5-9ef0-5db3b0474a58.gif)

Works pretty much like the CodePen one. It captures `console.log`s, but doesn't catch errors. 
It has history support like the console in the devtools (with the Up/Down keys).

You'll have to upgrade to `1.2.1` and include the `console` plugin:
https://ghinda.net/jotted/demos/console.html

**Comment by sobanhameed** [comment]
This is excellent @ghinda . On a side note a play button will be really handy as it will bring a bit of predictability on when things get executed.
