### ISSUE TITLE
Play Button to trigger execution

### ISSUE THREAD

**Issue by sobanhameed** [ghinda/jotted#9]
Currently jotted is in autorun mode. Can we have a way to turn off auto-run and a trigger to execute on some user action. Also if we could clear console on subsequent executions that will be awesome.

**Comment by ghinda** [comment]
Just letting you know I'm working on it. I'll probably release it sometime next week.

I've split the Console plugin feature in a separate issue. #10

**Comment by ghinda** [comment]
Released with `1.3.0`. It's a new plugin called `play`.

https://ghinda.net/jotted/demos/play.html

And a little preview:
![jotted-play-plugin](https://cloud.githubusercontent.com/assets/325171/13283627/73cbcdb6-daf7-11e5-894d-9cc8630deee0.gif)

**Comment by sobanhameed** [comment]
Thanks a ton.
